### ISSUE TITLE
NameError: name 'view' is not defined

### ISSUE THREAD

**Issue by fzorb** [marcuxyz/mvc-flask#28]
Hi,
I have recently started working with mvc-flask, however, I unfortunately cannot seem to get view() to work. (view is undefined)

**app/routes.py**
```py
from mvc_flask import Router

Router.get("/", "landing#route")
```

**app/controllers/landing_controller.py**
```py
from flask import session

class LandingController:
    def route(self):
        return view("index.html")
```

**app.py**
```py
from flask import Flask
from mvc_flask import FlaskMVC

app = Flask(__name__)
FlaskMVC(app)
```

**Comment by marcuxyz** [comment]
Sorry, I need update `readme`. You can use the `render_template` from flask module, instead `view` function.

`from flask import render_template`
