### ISSUE TITLE
FlaskMVC reinitialize app.template_folder and drop value settings in Flask initialize

### ISSUE THREAD

**Issue by bsa7** [marcuxyz/mvc-flask#29]
## This is cool mvc implementation, especially for me.
When i deep to Flask, i found the mvc-flask. It so like for me, because i'd RoR programmer.
So, i have to implement my folder structure identical to rails application.
But i found two incompatibilities with Ruby on Rails.
1. I can't set folder for templates, when initialize Flask:
```python
app = Flask(self.__name, template_folder = './app/views')
...
FlaskMVC(app, path = 'app')
```
After that, Flask searches templates in `./views` folder, but not in `./app/views` as i want. So, i try to propose pull-request to fix this behaviour.
With best regards to maintainers. FlaskMVC making python better (for me, for example).

**Comment by marcuxyz** [comment]
Hello @bsa7, fines? The `views` directory must be in `app` directory. Please see the sample https://github.com/marcuxyz/betravel-youtube/tree/main/app
