### ISSUE TITLE
Excluir a necessidade de um src path com o nome app

### ISSUE THREAD

**Issue by davimmilhome** [marcuxyz/mvc-flask#35]
Gostaria de sugerir a possibilidade de avoidar a necessidade da pasta core se charmar app, para poder utilizar a lib em projetos já existentes. Não sei qual o nível de complexidade dessa contribuição, até gostaria de fazer ela, porém, não tenho muito entendimento dessa parte

**Comment by marcuxyz** [comment]
Olá @davimmilhome , tudo bem?
O que seria _avoidar_?

O `middleware` aceita outros tipos de caminho também https://github.com/marcuxyz/mvc-flask/blob/main/mvc_flask/__init__.py#L11
E fique a vontade para contribuir , toda contribuição é bem-vinda :)

**Comment by marcuxyz** [comment]
você conseguiu validar @davimmilhome ?

**Comment by marcuxyz** [comment]
I'm close the problem because the author of the comment doesn't interact
