### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: index.html

### ISSUE THREAD

**Issue by bjenmonk** [marcuxyz/mvc-flask#9]
Hi
I cloned your code and while trying to use the example app I am getting this error

    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html

I tried creating a templates folder under the example directory and copied contents from the view folder to it. still the same error

Appreciate your help

**Comment by marcuxyz** [comment]
Hi @bjenmonk , 

change `templates` name to `views` . `mvc_flask` let me know if i helped you

**Comment by bjenmonk** [comment]
Hi Marcuxyz
tried that but didn't worked so I fixed it by changing 
def create_app():
    app = Flask(__name__, template_folder='views')

**Comment by marcuxyz** [comment]
Hey :)

You dont need configure the `template_folder` param, because, we will make this for you

https://github.com/marcuxyz/mvc_flask/blob/0c9a463a0744ff6ca072ac2eb5cf89bd25d0504d/mvc_flask/__init__.py#L14

Please, see this image:

![image](https://user-images.githubusercontent.com/9499562/132146383-7b2ad262-fd96-4b4f-acba-d797f7deca51.png)

is your directory like this?

**Comment by bjenmonk** [comment]
yes, I removed the  template_folder='views' and now it is working. not sure why. but thanks for your time

**Comment by marcuxyz** [comment]
You are welcome! :)

**Comment by nand2509** [comment]
Actually, its not working still have same problem.

**Comment by Sandesh-Ghimire** [comment]
app = Flask(__name__) instead of this only you can write as mentioned below.

app = Flask(__name__, template_folder='templates')  
//here templates is the folder name , check your folder name and write it inside single quotes.
this one worked for me.

**Comment by marcuxyz** [comment]
> yes, the folder structure is like that. I removed the template_folder='views' and now it is working. not sure why. but thanks for your time

please shared this repository, i will go review

**Comment by kssy-ks** [comment]
Hi there!
To solve TEMPLATE NOT FOUND ERROR in Flask I added "template_folder". So in short you get this:


    from flask import Flask, render_template
    
    app=Flask(__name__, template_folder='template')
    
    @app.route('/')
    def main():
        return render_template('home.html')
    
    app.run(debug=True)

**Comment by marcuxyz** [comment]
> Hi there! To solve TEMPLATE NOT FOUND ERROR in Flask I added "template_folder". So in short you get this:
> 
> ```
> from flask import Flask, render_template
> 
> app=Flask(__name__, template_folder='template')
> 
> @app.route('/')
> def main():
>     return render_template('home.html')
> 
> app.run(debug=True)
> ```

Hi @kssy-ks . Fines?
please shared this repository, i will go review.

**Comment by marcuxyz** [comment]
I tested here, its work for me :) see:

<img width="2560" alt="Captura de Tela 2023-04-05 às 23 23 12" src="https://user-images.githubusercontent.com/9499562/230256574-5c33ef3a-a584-4878-bc59-b174be4a2a65.png">

**Comment by ADyusuf12** [comment]
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: favicon.ico


Trying to create a portfolio website & I'm having a similar error to this right now. Can anyone help please?

This is what my code looks like right now:


from flask import Flask, render_template, url_for, request, redirect
from markupsafe import escape
import csv


app = Flask(__name__, template_folder='templates')


@app.route('/<string:page_name>')
def html_page(page_name):
	return render_template(page_name)

def write_to_csv(data):
	with open('./database.csv', newline='', mode='a') as database2:
		email = data["email"]
		subject = data["subject"]
		message = data["message"]
		csv_writer = csv.writer(database2, delimiter=',', quotechar='"', quoting = csv.QUOTE_MINIMAL)
		csv_writer.writerow([email,subject,message])

@app.route('/submit_form', methods=['POST', 'GET'])
def submit_form():
	if request.method == 'POST':
		data = request.form.to_dict()
		write_to_csv(data)
		return redirect('/thankyou.html')
	else:
		return 'Something went wrong. Try again!'

**Comment by marcuxyz** [comment]
> Sorry to say but this bug is really annoying. I tried all the suggested solutions but still face the same issue

Can you shared this repository?

**Comment by eyobmamo** [comment]
> app = Flask(**name**) instead of this only you can write as mentioned below.
> 
> app = Flask(**name**, template_folder='templates') //here templates is the folder name , check your folder name and write it inside single quotes. this one worked for me.

i try for a hour ....i works for me!!!!!!!!!!!
thanks a lot

**Comment by marcuxyz** [comment]
People, if you don't to describe the issue, it's hard to understand!!!!!

**Comment by ajanujaj** [comment]
<img width="1512" alt="image" src="https://github.com/marcuxyz/mvc-flask/assets/64679942/3894cf88-013b-43d5-84a9-05a8c99c26fd">


Hello @marcuxyz , I also facing the same issue
can you please help me with this.

**Comment by marcuxyz** [comment]
Hello @ajanujaj , It looks like it doesn't use the mvc-flask extension

**Comment by MuhamadZaki** [comment]
Cobalah, saya menyimpan folder resources -> remplates ( terdapat file html)
app=Flask(__name__, template_folder='resources/templates')

**Comment by iankb26** [comment]
Hi I having the same issue on mine . @marcuxyz can you help me  
![440420548_1453720012020229_5253463462240928238_n](https://github.com/marcuxyz/mvc-flask/assets/164335993/849023f7-3f8e-411c-a15e-d0629181ed10)
![440523839_458919010032819_8051616861470120693_n](https://github.com/marcuxyz/mvc-flask/assets/164335993/cfca853f-1fbc-4d2a-b834-8f57028f72e4)
![440441369_409729901835646_629505621840532910_n](https://github.com/marcuxyz/mvc-flask/assets/164335993/3751640a-4a3d-471b-962d-ab657fea0a30)

**Comment by marcuxyz** [comment]
@iankb26  you can send code to github and send me the link?

**Comment by iankb26** [comment]
@marcuxyz  https://github.com/iankb26/User-Interface                                                                                                                                Here's the link let me know what you think and I'm trying to use mvc method like what you showed on the previcus comments. Thanks for the help marcus :) ,

**Comment by marcuxyz** [comment]
@iankb26 Have you sent the correct code? I have not found the `mvc-flask` library.

**Comment by thanhhungk57** [comment]
I also have the same problem, can someone help me?
https://github.com/thanhhungk57/Mongodb-connect-fastapi.git

**Comment by marcuxyz** [comment]
@thanhhungk57 this project uses the `fastapi` project. mvc-flask only works on Flask. https://flask.palletsprojects.com/

**Comment by supreetbajaj2004** [comment]
hi @marcuxyz 

 i am also facing the same issue but i have tried everything using template folder variable changing the name of the folder but same facing the same issue 
![Screenshot (7)](https://github.com/user-attachments/assets/ba7d7562-d492-48ab-aff4-e2fe46ffcd9e)
![Screenshot (8)](https://github.com/user-attachments/assets/15b3a5de-72e8-480d-aa38-05974e22f1bd)

**Comment by marcuxyz** [comment]
Hi @supreetbajaj2004 ,
Do you install and use the extension: MVC-flask? in your images, look look that don't.

**Comment by supreetbajaj2004** [comment]
I will thanks for help@marcuxyz

**Comment by Reins981** [comment]
Such a long discussion for a simple bug. Why is that
